name: Autograding

on: 
  workflow_call:
    inputs:
      secrets:
        personal_access_token:
          required: true
        is_local:
          require: true
        pr_number:
          required: true
        repository:
          require: true

jobs:
  autograding:
    runs-on: ubuntu-22.04
    steps:
      - name: Installing Python (only on act)
        if: ${{ secrets.is_local }}
        run: | 
          apt update
          apt install -y python3 python3-pip git
      - name: Set repository name
        run: echo "REPO_NAME=$(echo ${{ secrets.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
      - name: All environment variables
        run: |
          echo ${{ secrets.internal_pat }}
          echo ${{ secrets.is_local }}
          echo ${{ secrets.pr_number }}
          echo ${{ secrets.repository }}
          echo ${{ env.REPO_NAME }}
      - name: Checking out current repository
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checking out solutions repository
        uses: actions/checkout@v4
        with:
          repository: git-mastery/solution-${{ env.REPO_NAME }}
          token: ${{ secrets.personal_access_token }}
          path: solution/
      - name: Setup Python (only on Github Actions)
        if: ${{ ! secrets.is_local }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Installing Python dependencies
        run: |
          pip install GitPython PyGithub
      - name: Run Python
        run: python3 grade.py
        working-directory: solution
            

